const exampleData = [
  {
    id: "Gvt07vmDx6EjcX-7GfMQPw",
    alias: "tibbitts-fern-hill-tacoma",
    name: "Tibbitts @ Fern Hill",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/M-S8mIRlOngKscO-qtb02A/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/tibbitts-fern-hill-tacoma?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 873,
    categories: [
      {
        alias: "newamerican",
        title: "New American",
      },
      {
        alias: "breakfast_brunch",
        title: "Breakfast & Brunch",
      },
    ],
    rating: 4.7,
    coordinates: {
      latitude: 47.1814448412222,
      longitude: -122.441734,
    },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "8237 S Park Ave",
      address2: null,
      address3: null,
      city: "Tacoma",
      zip_code: "98408",
      country: "US",
      state: "WA",
      display_address: ["8237 S Park Ave", "Tacoma, WA 98408"],
    },
    phone: "+12533271334",
    display_phone: "(253) 327-1334",
    distance: 965.2085235007302,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1000",
            end: "1400",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1000",
            end: "1400",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1000",
            end: "1400",
            day: 4,
          },
          {
            is_overnight: false,
            start: "0900",
            end: "1300",
            day: 5,
          },
          {
            is_overnight: false,
            start: "0900",
            end: "1300",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: false,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "http://www.tibbittsfernhillreservation.com",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "1M8itVxAE7vTf8_l9q9peQ",
    alias: "bar-bistro-tacoma",
    name: "Bar Bistro",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/rqh-spWlzWgHSDSz2mS6zw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/bar-bistro-tacoma?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 672,
    categories: [
      {
        alias: "cocktailbars",
        title: "Cocktail Bars",
      },
      {
        alias: "newamerican",
        title: "New American",
      },
      {
        alias: "steak",
        title: "Steakhouses",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 47.167026,
      longitude: -122.405636,
    },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "1718 99th St E",
      address2: "",
      address3: "",
      city: "Tacoma",
      zip_code: "98445",
      country: "US",
      state: "WA",
      display_address: ["1718 99th St E", "Tacoma, WA 98445"],
    },
    phone: "+12535373655",
    display_phone: "(253) 537-3655",
    distance: 2202.411243153536,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1600",
            end: "2100",
            day: 0,
          },
          {
            is_overnight: false,
            start: "1600",
            end: "2100",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1600",
            end: "2100",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1600",
            end: "2100",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1600",
            end: "2200",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1600",
            end: "2200",
            day: 5,
          },
          {
            is_overnight: false,
            start: "1600",
            end: "2100",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: false,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "http://barbistrotacoma.com/#menus",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "Ve_xVlv7c0tzSHtUWwNiJA",
    alias: "hong-kong-restaurant-tacoma",
    name: "Hong Kong Restaurant",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/IoZdWcCzogwWpRa_QFo4tg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/hong-kong-restaurant-tacoma?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 228,
    categories: [
      {
        alias: "chinese",
        title: "Chinese",
      },
    ],
    rating: 3.6,
    coordinates: {
      latitude: 47.1758422851562,
      longitude: -122.433280944824,
    },
    transactions: ["delivery", "pickup"],
    price: "$$",
    location: {
      address1: "8843 Pacific Ave",
      address2: "",
      address3: "",
      city: "Tacoma",
      zip_code: "98444",
      country: "US",
      state: "WA",
      display_address: ["8843 Pacific Ave", "Tacoma, WA 98444"],
    },
    phone: "+12535312533",
    display_phone: "(253) 531-2533",
    distance: 320.3502562573441,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1200",
            end: "2100",
            day: 5,
          },
          {
            is_overnight: false,
            start: "1200",
            end: "2100",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: false,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: null,
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "nORIFrx9QuSYwZXD2sO64Q",
    alias: "carne-aqui-tacoma",
    name: "Carne Aqui",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/s4PlLtUpvh6o6GIzenMyVQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/carne-aqui-tacoma?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 430,
    categories: [
      {
        alias: "argentine",
        title: "Argentine",
      },
      {
        alias: "latin",
        title: "Latin American",
      },
      {
        alias: "mexican",
        title: "Mexican",
      },
    ],
    rating: 4.4,
    coordinates: {
      latitude: 47.12511333,
      longitude: -122.43532833,
    },
    transactions: ["delivery", "pickup"],
    price: "$$",
    location: {
      address1: "14506 Pacific Ave S",
      address2: null,
      address3: "",
      city: "Tacoma",
      zip_code: "98444",
      country: "US",
      state: "WA",
      display_address: ["14506 Pacific Ave S", "Tacoma, WA 98444"],
    },
    phone: "+12535356328",
    display_phone: "(253) 535-6328",
    distance: 5831.835718101499,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1200",
            end: "2100",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1200",
            end: "2100",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1200",
            end: "2100",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1200",
            end: "2100",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1200",
            end: "2100",
            day: 5,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: false,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "http://www.carneaqui.com/menu",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "uJRJJvVpdP5zZsy0EQwmDA",
    alias: "marzano-italian-restaurant-tacoma",
    name: "Marzano Italian Restaurant",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/_jPpGdrtsE9eAsyMsVm7Yw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/marzano-italian-restaurant-tacoma?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 657,
    categories: [
      {
        alias: "italian",
        title: "Italian",
      },
      {
        alias: "salad",
        title: "Salad",
      },
      {
        alias: "pizza",
        title: "Pizza",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 47.1460188285106,
      longitude: -122.439098232019,
    },
    transactions: ["delivery", "pickup"],
    price: "$$",
    location: {
      address1: "516 Garfield St S",
      address2: "",
      address3: "",
      city: "Tacoma",
      zip_code: "98444",
      country: "US",
      state: "WA",
      display_address: ["516 Garfield St S", "Tacoma, WA 98444"],
    },
    phone: "+12535374191",
    display_phone: "(253) 537-4191",
    distance: 3567.213373807346,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1600",
            end: "2030",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1600",
            end: "2030",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1600",
            end: "2030",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1600",
            end: "2100",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1600",
            end: "2100",
            day: 5,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: false,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "https://www.dinemarzano.com/dinner",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "ZSmtQJvp4NPJWFBvbhaPvQ",
    alias: "melon-seed-deli-and-frozen-yogurt-tacoma",
    name: "Melon Seed Deli & Frozen Yogurt",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/u53fEiP7qArri1tDRnSDmw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/melon-seed-deli-and-frozen-yogurt-tacoma?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 891,
    categories: [
      {
        alias: "sandwiches",
        title: "Sandwiches",
      },
      {
        alias: "icecream",
        title: "Ice Cream & Frozen Yogurt",
      },
      {
        alias: "salad",
        title: "Salad",
      },
    ],
    rating: 4.8,
    coordinates: {
      latitude: 47.231709,
      longitude: -122.486536,
    },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "3807 Center St",
      address2: "Ste D",
      address3: "",
      city: "Tacoma",
      zip_code: "98409",
      country: "US",
      state: "WA",
      display_address: ["3807 Center St", "Ste D", "Tacoma, WA 98409"],
    },
    phone: "+12532790029",
    display_phone: "(253) 279-0029",
    distance: 7369.498396491064,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 5,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: false,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "bs85QhWFcJFcHzsqTF4yPQ",
    alias: "elmers-restaurant-tacoma",
    name: "Elmer's Restaurant",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/IJSlkMePUWHvp_v-Yy1c-g/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/elmers-restaurant-tacoma?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 546,
    categories: [
      {
        alias: "breakfast_brunch",
        title: "Breakfast & Brunch",
      },
      {
        alias: "diners",
        title: "Diners",
      },
      {
        alias: "tradamerican",
        title: "American",
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 47.1897048950195,
      longitude: -122.460105895996,
    },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "7427 S Hosmer St",
      address2: "",
      address3: "",
      city: "Tacoma",
      zip_code: "98408",
      country: "US",
      state: "WA",
      display_address: ["7427 S Hosmer St", "Tacoma, WA 98408"],
    },
    phone: "+12534730855",
    display_phone: "(253) 473-0855",
    distance: 2616.4947975961722,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "0600",
            end: "2200",
            day: 0,
          },
          {
            is_overnight: false,
            start: "0600",
            end: "2200",
            day: 1,
          },
          {
            is_overnight: false,
            start: "0600",
            end: "2200",
            day: 2,
          },
          {
            is_overnight: false,
            start: "0600",
            end: "2200",
            day: 3,
          },
          {
            is_overnight: false,
            start: "0600",
            end: "2200",
            day: 4,
          },
          {
            is_overnight: false,
            start: "0600",
            end: "2200",
            day: 5,
          },
          {
            is_overnight: false,
            start: "0600",
            end: "2200",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "http://eatatelmers.com/menu/",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "PqCJCmRy0Cehq_cOrLoGFg",
    alias: "moctezumas-mexican-restaurant-and-tequila-bar-tacoma",
    name: "Moctezuma's Mexican Restaurant & Tequila Bar",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/vVITB67n9fgun1vtAWUHRg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/moctezumas-mexican-restaurant-and-tequila-bar-tacoma?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 1241,
    categories: [
      {
        alias: "mexican",
        title: "Mexican",
      },
      {
        alias: "bars",
        title: "Bars",
      },
    ],
    rating: 3.9,
    coordinates: {
      latitude: 47.205954,
      longitude: -122.492476,
    },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "4102 S 56th St",
      address2: "",
      address3: "",
      city: "Tacoma",
      zip_code: "98409",
      country: "US",
      state: "WA",
      display_address: ["4102 S 56th St", "Tacoma, WA 98409"],
    },
    phone: "+12534745593",
    display_phone: "(253) 474-5593",
    distance: 5659.924261585052,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 0,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2300",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2300",
            day: 5,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: false,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "Bri4bDh0xJFDiFMXnQ4QWA",
    alias: "indita-mia-tacoma",
    name: "Indita Mia",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/wIPM5-e4w_z49RnbXckvEw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/indita-mia-tacoma?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 190,
    categories: [
      {
        alias: "mexican",
        title: "Mexican",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 47.246649,
      longitude: -122.433734,
    },
    transactions: ["restaurant_reservation"],
    price: "$$",
    location: {
      address1: "1715 Dock St",
      address2: null,
      address3: "",
      city: "Tacoma",
      zip_code: "98402",
      country: "US",
      state: "WA",
      display_address: ["1715 Dock St", "Tacoma, WA 98402"],
    },
    phone: "+12533011784",
    display_phone: "(253) 301-1784",
    distance: 7688.8112943809065,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1600",
            end: "2200",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1600",
            end: "2200",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1600",
            end: "2200",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1600",
            end: "2200",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 5,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2000",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: false,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "https://www.inditamia.restaurant/#Menu",
      open24_hours: null,
      waitlist_reservation: true,
    },
  },
  {
    id: "ifd9Ywp8rkuZo0JrzvGA1g",
    alias: "my-4-sons-bbq-tacoma-3",
    name: "My 4 Sons BBQ",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/YjSujCvZDB6mJOS13LL0Zw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/my-4-sons-bbq-tacoma-3?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 251,
    categories: [
      {
        alias: "bbq",
        title: "Barbeque",
      },
    ],
    rating: 4.4,
    coordinates: {
      latitude: 47.16735489179088,
      longitude: -122.40514757760036,
    },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "9823 Portland Ave E",
      address2: "",
      address3: null,
      city: "Tacoma",
      zip_code: "98445",
      country: "US",
      state: "WA",
      display_address: ["9823 Portland Ave E", "Tacoma, WA 98445"],
    },
    phone: "+12537774677",
    display_phone: "(253) 777-4677",
    distance: 2214.858328073924,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1100",
            end: "1900",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "1900",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "1900",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "1900",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "1900",
            day: 5,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: false,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: null,
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "BniPe8-wMnXr_5BPQ3NkkQ",
    alias: "little-jerrys-tacoma",
    name: "Little Jerry's",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/IzMC5IgkpdKhUb2hkzRV-Q/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/little-jerrys-tacoma?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 456,
    categories: [
      {
        alias: "breakfast_brunch",
        title: "Breakfast & Brunch",
      },
      {
        alias: "burgers",
        title: "Burgers",
      },
      {
        alias: "tradamerican",
        title: "American",
      },
    ],
    rating: 4.2,
    coordinates: {
      latitude: 47.181669,
      longitude: -122.441503,
    },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "8233 S Park Ave",
      address2: "",
      address3: "",
      city: "Tacoma",
      zip_code: "98408",
      country: "US",
      state: "WA",
      display_address: ["8233 S Park Ave", "Tacoma, WA 98408"],
    },
    phone: "+12534742435",
    display_phone: "(253) 474-2435",
    distance: 962.2675272016214,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "0700",
            end: "1500",
            day: 0,
          },
          {
            is_overnight: false,
            start: "0700",
            end: "1500",
            day: 1,
          },
          {
            is_overnight: false,
            start: "0700",
            end: "1500",
            day: 2,
          },
          {
            is_overnight: false,
            start: "0700",
            end: "1500",
            day: 3,
          },
          {
            is_overnight: false,
            start: "0700",
            end: "1500",
            day: 4,
          },
          {
            is_overnight: false,
            start: "0700",
            end: "1500",
            day: 5,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: false,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "3aCI5CH8lPuDTkoZWYe_5g",
    alias: "el-pulgarcito-iii-lakewood-2",
    name: "El Pulgarcito III",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/ZQHQoRHukXqKw7-B3mm7MQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/el-pulgarcito-iii-lakewood-2?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 171,
    categories: [
      {
        alias: "salvadoran",
        title: "Salvadoran",
      },
    ],
    rating: 4.4,
    coordinates: {
      latitude: 47.17958090555558,
      longitude: -122.48456414491028,
    },
    transactions: ["delivery"],
    price: "$",
    location: {
      address1: "8534 S Tacoma Way",
      address2: "Ste C",
      address3: "",
      city: "Lakewood",
      zip_code: "98499",
      country: "US",
      state: "WA",
      display_address: ["8534 S Tacoma Way", "Ste C", "Lakewood, WA 98499"],
    },
    phone: "+12535822212",
    display_phone: "(253) 582-2212",
    distance: 4105.488618834713,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1000",
            end: "2200",
            day: 0,
          },
          {
            is_overnight: false,
            start: "1000",
            end: "2200",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1000",
            end: "2200",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1000",
            end: "2200",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1000",
            end: "2200",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1000",
            end: "2200",
            day: 5,
          },
          {
            is_overnight: false,
            start: "1000",
            end: "2200",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "http://www.restaurantelpulgarcito.com/14401.html",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "JtEwHTXY5dVvqw2zw3jkYQ",
    alias: "bloom-thai-cuisine-lakewood",
    name: "Bloom Thai Cuisine",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/o6r_n68_iGNoNO7ZhAYp0A/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/bloom-thai-cuisine-lakewood?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 114,
    categories: [
      {
        alias: "thai",
        title: "Thai",
      },
    ],
    rating: 4.9,
    coordinates: {
      latitude: 47.1905615,
      longitude: -122.51214081712888,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "7402 Custer Rd W",
      address2: "Ste 103-104",
      address3: null,
      city: "Lakewood",
      zip_code: "98499",
      country: "US",
      state: "WA",
      display_address: [
        "7402 Custer Rd W",
        "Ste 103-104",
        "Lakewood, WA 98499",
      ],
    },
    phone: "+12067418433",
    display_phone: "(206) 741-8433",
    distance: 6350.108470432343,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1200",
            end: "1500",
            day: 0,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "1500",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "1500",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2000",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2000",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1200",
            end: "2000",
            day: 5,
          },
          {
            is_overnight: false,
            start: "1200",
            end: "2000",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: false,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: null,
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "6F-jzNztrvOySA-Qj5W0rg",
    alias: "loak-toung-thai-tacoma-5",
    name: "Loak Toung Thai",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/mKn93_18Nbnnu9K6KJygaQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/loak-toung-thai-tacoma-5?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 328,
    categories: [
      {
        alias: "thai",
        title: "Thai",
      },
    ],
    rating: 4.6,
    coordinates: {
      latitude: 47.2315723,
      longitude: -122.4866547,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "3807 Center St",
      address2: "Ste B",
      address3: "",
      city: "Tacoma",
      zip_code: "98409",
      country: "US",
      state: "WA",
      display_address: ["3807 Center St", "Ste B", "Tacoma, WA 98409"],
    },
    phone: "+12532489813",
    display_phone: "(253) 248-9813",
    distance: 7362.262210387401,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1100",
            end: "1430",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1630",
            end: "2000",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "1430",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1630",
            end: "2000",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "1430",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1630",
            end: "2000",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2000",
            day: 5,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: false,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "http://www.loaktoungthai.com/menu",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "sQTL322sxd676g_QluOjmg",
    alias: "zesty-steakhouse-lakewood",
    name: "Zesty Steakhouse",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/eH0s6-uXaULIXHJwwu1yEg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/zesty-steakhouse-lakewood?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 181,
    categories: [
      {
        alias: "seafood",
        title: "Seafood",
      },
      {
        alias: "steak",
        title: "Steakhouses",
      },
      {
        alias: "sportsbars",
        title: "Sports Bars",
      },
    ],
    rating: 3.9,
    coordinates: {
      latitude: 47.16773,
      longitude: -122.51108,
    },
    transactions: ["delivery", "pickup"],
    price: "$$",
    location: {
      address1: "9905 Bridgeport Way SW",
      address2: null,
      address3: null,
      city: "Lakewood",
      zip_code: "98499",
      country: "US",
      state: "WA",
      display_address: ["9905 Bridgeport Way SW", "Lakewood, WA 98499"],
    },
    phone: "+12533007993",
    display_phone: "(253) 300-7993",
    distance: 6204.58256106634,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1200",
            end: "2200",
            day: 0,
          },
          {
            is_overnight: false,
            start: "1200",
            end: "2200",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1200",
            end: "2200",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1200",
            end: "2200",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1200",
            end: "0000",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1200",
            end: "0000",
            day: 5,
          },
          {
            is_overnight: false,
            start: "1200",
            end: "2200",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "https://www.zestycajungrill.com/menus",
      open24_hours: null,
      waitlist_reservation: true,
    },
  },
  {
    id: "bKSYx3ds8pHlI-nP3xPPKw",
    alias: "ho-soon-yi-lakewood",
    name: "Ho Soon Yi",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/qXSypWNVBI7kH0tiMGa_nw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/ho-soon-yi-lakewood?adjust_creative=0FOzNFb_BrecDsS72i0mAA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=0FOzNFb_BrecDsS72i0mAA",
    review_count: 369,
    categories: [
      {
        alias: "korean",
        title: "Korean",
      },
    ],
    rating: 4.4,
    coordinates: {
      latitude: 47.1802574,
      longitude: -122.48332079478332,
    },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "8501 S Tacoma Way",
      address2: null,
      address3: "",
      city: "Lakewood",
      zip_code: "98499",
      country: "US",
      state: "WA",
      display_address: ["8501 S Tacoma Way", "Lakewood, WA 98499"],
    },
    phone: "+12535844572",
    display_phone: "(253) 584-4572",
    distance: 4016.5931328160486,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 0,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 5,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: null,
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
];
module.exports = exampleData;
